"""add payment tables and system config

Revision ID: 0b1257162b77
Revises: f71224133188
Create Date: 2026-03-24 17:00:19.254085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0b1257162b77'
down_revision: Union[str, Sequence[str], None] = 'f71224133188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 首先处理 users 表的 enterprise_id 和 is_enterprise_admin 字段
    # 先更新 NULL 值为默认值
    op.execute("UPDATE users SET enterprise_id = '' WHERE enterprise_id IS NULL")
    op.execute("UPDATE users SET is_enterprise_admin = 0 WHERE is_enterprise_admin IS NULL")

    # 然后修改为 NOT NULL
    op.alter_column('users', 'enterprise_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               nullable=False,
               existing_comment='所属企业ID')
    op.alter_column('users', 'is_enterprise_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_comment='是否企业管理员')

    # 创建 system_configs 表
    op.create_table('system_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False, comment='配置键'),
    sa.Column('value', sa.String(length=500), nullable=False, comment='配置值'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='配置描述'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configs_key'), 'system_configs', ['key'], unique=True)

    # 初始化默认配置：积分兑换比例
    from datetime import datetime
    from sqlalchemy import table, column

    # 使用 SQLAlchemy 表对象来避免 MySQL 保留字问题
    system_configs_table = table('system_configs',
        column('key', sa.String(length=50)),
        column('value', sa.String(length=500)),
        column('description', sa.String(length=200)),
        column('created_at', sa.DateTime()),
        column('updated_at', sa.DateTime())
    )
    op.execute(
        system_configs_table.insert().values(
            key='points_per_yuan',
            value='100',
            description='1元对应的积分数量',
            created_at=datetime.now(),
            updated_at=datetime.now()
        )
    )

    # 创建 payment_orders 表
    op.create_table('payment_orders',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('out_trade_no', sa.String(length=64), nullable=False, comment='商户订单号'),
    sa.Column('third_trade_no', sa.String(length=64), nullable=True, comment='工行流水号'),
    sa.Column('amount', sa.Integer(), nullable=False, comment='金额（分）'),
    sa.Column('status', sa.Enum('created', 'processing', 'paid', 'failed', 'cancelled', 'timeout', name='paymentorderstatus'), nullable=False),
    sa.Column('pay_channel', sa.String(length=20), nullable=False, comment='支付渠道'),
    sa.Column('business_type', sa.String(length=20), nullable=False, comment='业务类型'),
    sa.Column('business_id', sa.String(length=36), nullable=True, comment='业务ID'),
    sa.Column('pay_url', sa.String(length=512), nullable=True, comment='支付URL'),
    sa.Column('qr_code_data', sa.String(length=512), nullable=True, comment='二维码数据'),
    sa.Column('icbc_response', sa.JSON(), nullable=True, comment='工行完整响应'),
    sa.Column('submitted_at', sa.DateTime(), nullable=True, comment='发起时间'),
    sa.Column('paid_at', sa.DateTime(), nullable=True, comment='支付时间'),
    sa.Column('expire_at', sa.DateTime(), nullable=True, comment='超时时间'),
    sa.Column('notified_at', sa.DateTime(), nullable=True, comment='回调到达时间'),
    sa.Column('notify_data', sa.JSON(), nullable=True, comment='回调原始数据'),
    sa.Column('notify_verify_result', sa.Boolean(), nullable=True, comment='回调验签结果'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_created', 'payment_orders', ['created_at'], unique=False)
    op.create_index('idx_payment_user_status', 'payment_orders', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_payment_orders_out_trade_no'), 'payment_orders', ['out_trade_no'], unique=True)
    op.create_index(op.f('ix_payment_orders_status'), 'payment_orders', ['status'], unique=False)
    op.create_index(op.f('ix_payment_orders_user_id'), 'payment_orders', ['user_id'], unique=False)

    # 为 point_transactions 表添加支付相关字段
    op.add_column('point_transactions', sa.Column('payment_id', mysql.CHAR(length=36), nullable=True, comment='关联的支付订单ID'))
    op.add_column('point_transactions', sa.Column('payment_amount', sa.Integer(), nullable=True, comment='充值金额（分）'))

    # 添加外键约束（仅当 enterprises 表存在时）
    # 注意：如果 enterprises 表不存在，这步可能会失败
    # op.create_foreign_key(None, 'users', 'enterprises', ['enterprise_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除默认配置
    from sqlalchemy import table, column
    system_configs_table = table('system_configs',
        column('key', sa.String(length=50))
    )
    op.execute(
        system_configs_table.delete().where(
            system_configs_table.c.key == 'points_per_yuan'
        )
    )

    # 删除 point_transactions 的支付相关字段
    op.drop_column('point_transactions', 'payment_amount')
    op.drop_column('point_transactions', 'payment_id')

    # 删除 payment_orders 表及其索引
    op.drop_index(op.f('ix_payment_orders_user_id'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_status'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_out_trade_no'), table_name='payment_orders')
    op.drop_index('idx_payment_user_status', table_name='payment_orders')
    op.drop_index('idx_payment_created', table_name='payment_orders')
    op.drop_table('payment_orders')

    # 删除 system_configs 表及其索引
    op.drop_index(op.f('ix_system_configs_key'), table_name='system_configs')
    op.drop_table('system_configs')

    # 恢复 users 表字段为可空（如果需要）
    op.alter_column('users', 'is_enterprise_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_comment='是否企业管理员')
    op.alter_column('users', 'enterprise_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               nullable=True,
               existing_comment='所属企业ID')
    # ### end Alembic commands ###
