"""add_icbc_order_fields

Revision ID: 32f057d65b28
Revises: 3ae5f8556ec4
Create Date: 2026-03-26 23:33:34.279647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32f057d65b28'
down_revision: Union[str, Sequence[str], None] = '3ae5f8556ec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_orders', sa.Column('goods_name', sa.String(length=40), nullable=True, comment='商品名称'))
    op.add_column('payment_orders', sa.Column('attach', sa.String(length=127), nullable=True, comment='附加数据，原样返回'))
    op.add_column('payment_orders', sa.Column('support_app_type', sa.String(length=10), nullable=True, comment='支持的支付方式位图'))
    op.add_column('payment_orders', sa.Column('msg_id', sa.String(length=40), nullable=True, comment='消息通讯唯一编号'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_orders', 'msg_id')
    op.drop_column('payment_orders', 'support_app_type')
    op.drop_column('payment_orders', 'attach')
    op.drop_column('payment_orders', 'goods_name')
    # ### end Alembic commands ###
