"""feat: 添加AI工具配置数据库模型

Revision ID: 47a947d71251
Revises: g2h3i4j5k6l7
Create Date: 2026-03-20 20:31:21.949505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '47a947d71251'
down_revision: Union[str, Sequence[str], None] = 'g2h3i4j5k6l7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('navigation_modules',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('toolset', 'page', name='navigationmoduletype'), nullable=False),
    sa.Column('config_source', sa.String(length=100), nullable=True),
    sa.Column('page_path', sa.String(length=100), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_navigation_module_order', 'navigation_modules', ['order'], unique=False)
    op.create_table('toolsets',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('toolset_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_toolsets_toolset_id'), 'toolsets', ['toolset_id'], unique=True)
    op.create_table('ai_tool_categories',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('toolset_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['toolset_id'], ['toolsets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_tool_categories_toolset_id'), 'ai_tool_categories', ['toolset_id'], unique=False)
    op.create_table('ai_tools',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('tool_id', sa.String(length=50), nullable=False),
    sa.Column('toolset_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('category_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('type', sa.Enum('normal', 'media', name='aitooltype'), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=True),
    sa.Column('media_type', sa.String(length=20), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('welcome_message', sa.Text(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['ai_tool_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['toolset_id'], ['toolsets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_tool_category_order', 'ai_tools', ['category_id', 'order'], unique=False)
    op.create_index('idx_ai_tool_toolset_order', 'ai_tools', ['toolset_id', 'order'], unique=False)
    op.create_index(op.f('ix_ai_tools_tool_id'), 'ai_tools', ['tool_id'], unique=True)
    op.create_index(op.f('ix_ai_tools_toolset_id'), 'ai_tools', ['toolset_id'], unique=False)
    op.create_index(op.f('ix_ai_tools_visible'), 'ai_tools', ['visible'], unique=False)
    # 注释掉索引操作：idx_message_id 被外键引用，无法删除
    # op.drop_index('idx_message_id', table_name='artifacts')
    # op.create_index(op.f('ix_artifacts_message_id'), 'artifacts', ['message_id'], unique=False)
    op.drop_index('idx_category_id', table_name='common_tools')
    op.drop_index('idx_category_order', table_name='common_tools')
    op.drop_index('idx_visible', table_name='common_tools')
    op.create_index(op.f('ix_common_tools_category_id'), 'common_tools', ['category_id'], unique=False)
    op.create_index(op.f('ix_common_tools_visible'), 'common_tools', ['visible'], unique=False)
    op.alter_column('course_categories', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='目录ID（UUID）',
               existing_nullable=False)
    op.alter_column('course_categories', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='目录名称',
               existing_nullable=False)
    op.alter_column('course_categories', 'parent_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='父目录ID（NULL表示根目录）',
               existing_nullable=True)
    op.alter_column('course_categories', 'order',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='排序顺序',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('course_categories', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('course_categories', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index('idx_parent_id', table_name='course_categories')
    op.drop_index('idx_parent_order', table_name='course_categories')
    op.create_index('idx_course_category_parent_order', 'course_categories', ['parent_id', 'order'], unique=False)
    op.create_index(op.f('ix_course_categories_parent_id'), 'course_categories', ['parent_id'], unique=False)
    op.drop_table_comment(
        'course_categories',
        existing_comment='文档目录表',
        schema=None
    )
    op.alter_column('course_documents', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='文档ID（UUID）',
               existing_nullable=False)
    op.alter_column('course_documents', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='文档标题',
               existing_nullable=False)
    op.alter_column('course_documents', 'summary',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment=None,
               existing_comment='文档摘要',
               existing_nullable=False)
    op.alter_column('course_documents', 'file_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='Markdown文件路径（相对于static目录）',
               existing_nullable=False)
    op.alter_column('course_documents', 'category_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='所属目录ID',
               existing_nullable=False)
    op.alter_column('course_documents', 'order',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='排序顺序',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('course_documents', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('course_documents', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index('idx_category_id', table_name='course_documents')
    op.drop_index('idx_category_order', table_name='course_documents')
    op.create_index('idx_course_document_category_order', 'course_documents', ['category_id', 'order'], unique=False)
    op.create_index(op.f('ix_course_documents_category_id'), 'course_documents', ['category_id'], unique=False)
    op.drop_table_comment(
        'course_documents',
        existing_comment='文档表',
        schema=None
    )
    op.drop_column('course_documents', 'content')
    op.alter_column('messages', 'media_content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='多模态内容JSON字符串',
               existing_comment='多模态内容JSON字符串（图片、音频、视频等）',
               existing_nullable=True)
    op.drop_index('idx_created_at', table_name='messages')
    op.drop_index('idx_session_id', table_name='messages')
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.drop_index('idx_tool_id', table_name='sessions')
    op.drop_index('idx_updated_at', table_name='sessions')
    op.drop_index('idx_user_id', table_name='sessions')
    op.create_index(op.f('ix_sessions_tool_id'), 'sessions', ['tool_id'], unique=False)
    op.create_index(op.f('ix_sessions_updated_at'), 'sessions', ['updated_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.alter_column('token_usage_logs', 'user_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('token_usage_logs', 'session_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='会话ID',
               existing_nullable=False)
    op.alter_column('token_usage_logs', 'message_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='消息ID',
               existing_nullable=False)
    op.alter_column('token_usage_logs', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('(now())'))
    op.drop_index('idx_token_logs_message', table_name='token_usage_logs')
    op.drop_index('idx_token_logs_provider', table_name='token_usage_logs')
    op.drop_index('idx_token_logs_session', table_name='token_usage_logs')
    op.drop_index('idx_token_logs_user_date', table_name='token_usage_logs')
    op.create_index('idx_token_provider', 'token_usage_logs', ['model_provider'], unique=False)
    op.create_index('idx_token_session', 'token_usage_logs', ['session_id'], unique=False)
    op.create_index('idx_token_user_date', 'token_usage_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_token_usage_logs_created_at'), 'token_usage_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_token_usage_logs_message_id'), 'token_usage_logs', ['message_id'], unique=False)
    op.create_index(op.f('ix_token_usage_logs_session_id'), 'token_usage_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_token_usage_logs_user_id'), 'token_usage_logs', ['user_id'], unique=False)
    op.drop_table_comment(
        'token_usage_logs',
        existing_comment='Token使用日志表，用于计费和审计',
        schema=None
    )
    op.drop_index('idx_order', table_name='tool_categories')
    op.create_index(op.f('ix_tool_categories_order'), 'tool_categories', ['order'], unique=False)
    op.drop_index('idx_email', table_name='users')
    op.drop_index('idx_is_admin', table_name='users')
    op.drop_index('idx_phone', table_name='users')
    op.drop_index('idx_username', table_name='users')
    op.create_index(op.f('ix_users_is_admin'), 'users', ['is_admin'], unique=False)
    op.drop_column('users', 'updated_at')
    op.alter_column('work_categories', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='分类ID（UUID）',
               existing_nullable=False)
    op.alter_column('work_categories', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='分类名称',
               existing_nullable=False)
    op.alter_column('work_categories', 'icon',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='分类图标（heroicons名称）',
               existing_nullable=True)
    op.alter_column('work_categories', 'order',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='排序顺序',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('work_categories', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('work_categories', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index('idx_order', table_name='work_categories')
    op.create_index(op.f('ix_work_categories_order'), 'work_categories', ['order'], unique=False)
    op.drop_table_comment(
        'work_categories',
        existing_comment='作品分类表',
        schema=None
    )
    op.alter_column('works', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='作品ID（UUID）',
               existing_nullable=False)
    op.alter_column('works', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='作品名称',
               existing_nullable=False)
    op.alter_column('works', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='作品描述',
               existing_nullable=False)
    op.alter_column('works', 'category_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='所属分类ID',
               existing_nullable=False)
    op.alter_column('works', 'icon',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='图标标识（heroicons名称）',
               existing_nullable=True)
    op.alter_column('works', 'html_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='HTML文件路径（相对于static目录）',
               existing_nullable=False)
    op.alter_column('works', 'order',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='排序顺序',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('works', 'visible',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否可见',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('works', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('works', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index('idx_category_id', table_name='works')
    op.drop_index('idx_category_order', table_name='works')
    op.drop_index('idx_visible', table_name='works')
    op.create_index(op.f('ix_works_category_id'), 'works', ['category_id'], unique=False)
    op.create_index(op.f('ix_works_visible'), 'works', ['visible'], unique=False)
    op.drop_table_comment(
        'works',
        existing_comment='作品表',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'works',
        '作品表',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_works_visible'), table_name='works')
    op.drop_index(op.f('ix_works_category_id'), table_name='works')
    op.create_index('idx_visible', 'works', ['visible'], unique=False)
    op.create_index('idx_category_order', 'works', ['category_id', 'order'], unique=False)
    op.create_index('idx_category_id', 'works', ['category_id'], unique=False)
    op.alter_column('works', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('works', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('works', 'visible',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否可见',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('works', 'order',
               existing_type=mysql.INTEGER(),
               comment='排序顺序',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('works', 'html_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='HTML文件路径（相对于static目录）',
               existing_nullable=False)
    op.alter_column('works', 'icon',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='图标标识（heroicons名称）',
               existing_nullable=True)
    op.alter_column('works', 'category_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='所属分类ID',
               existing_nullable=False)
    op.alter_column('works', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='作品描述',
               existing_nullable=False)
    op.alter_column('works', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='作品名称',
               existing_nullable=False)
    op.alter_column('works', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='作品ID（UUID）',
               existing_nullable=False)
    op.create_table_comment(
        'work_categories',
        '作品分类表',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_work_categories_order'), table_name='work_categories')
    op.create_index('idx_order', 'work_categories', ['order'], unique=False)
    op.alter_column('work_categories', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('work_categories', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('work_categories', 'order',
               existing_type=mysql.INTEGER(),
               comment='排序顺序',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('work_categories', 'icon',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='分类图标（heroicons名称）',
               existing_nullable=True)
    op.alter_column('work_categories', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='分类名称',
               existing_nullable=False)
    op.alter_column('work_categories', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='分类ID（UUID）',
               existing_nullable=False)
    op.add_column('users', sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=True))
    op.drop_index(op.f('ix_users_is_admin'), table_name='users')
    op.create_index('idx_username', 'users', ['username'], unique=False)
    op.create_index('idx_phone', 'users', ['phone'], unique=False)
    op.create_index('idx_is_admin', 'users', ['is_admin'], unique=False)
    op.create_index('idx_email', 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_tool_categories_order'), table_name='tool_categories')
    op.create_index('idx_order', 'tool_categories', ['order'], unique=False)
    op.create_table_comment(
        'token_usage_logs',
        'Token使用日志表，用于计费和审计',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_token_usage_logs_user_id'), table_name='token_usage_logs')
    op.drop_index(op.f('ix_token_usage_logs_session_id'), table_name='token_usage_logs')
    op.drop_index(op.f('ix_token_usage_logs_message_id'), table_name='token_usage_logs')
    op.drop_index(op.f('ix_token_usage_logs_created_at'), table_name='token_usage_logs')
    op.drop_index('idx_token_user_date', table_name='token_usage_logs')
    op.drop_index('idx_token_session', table_name='token_usage_logs')
    op.drop_index('idx_token_provider', table_name='token_usage_logs')
    op.create_index('idx_token_logs_user_date', 'token_usage_logs', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_token_logs_session', 'token_usage_logs', ['session_id'], unique=False)
    op.create_index('idx_token_logs_provider', 'token_usage_logs', ['model_provider'], unique=False)
    op.create_index('idx_token_logs_message', 'token_usage_logs', ['message_id'], unique=False)
    op.alter_column('token_usage_logs', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('token_usage_logs', 'message_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='消息ID',
               existing_nullable=False)
    op.alter_column('token_usage_logs', 'session_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='会话ID',
               existing_nullable=False)
    op.alter_column('token_usage_logs', 'user_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='用户ID',
               existing_nullable=False)
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_updated_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_tool_id'), table_name='sessions')
    op.create_index('idx_user_id', 'sessions', ['user_id'], unique=False)
    op.create_index('idx_updated_at', 'sessions', ['updated_at'], unique=False)
    op.create_index('idx_tool_id', 'sessions', ['tool_id'], unique=False)
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.create_index('idx_session_id', 'messages', ['session_id'], unique=False)
    op.create_index('idx_created_at', 'messages', ['created_at'], unique=False)
    op.alter_column('messages', 'media_content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='多模态内容JSON字符串（图片、音频、视频等）',
               existing_comment='多模态内容JSON字符串',
               existing_nullable=True)
    op.add_column('course_documents', sa.Column('content', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.create_table_comment(
        'course_documents',
        '文档表',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_course_documents_category_id'), table_name='course_documents')
    op.drop_index('idx_course_document_category_order', table_name='course_documents')
    op.create_index('idx_category_order', 'course_documents', ['category_id', 'order'], unique=False)
    op.create_index('idx_category_id', 'course_documents', ['category_id'], unique=False)
    op.alter_column('course_documents', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('course_documents', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('course_documents', 'order',
               existing_type=mysql.INTEGER(),
               comment='排序顺序',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('course_documents', 'category_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='所属目录ID',
               existing_nullable=False)
    op.alter_column('course_documents', 'file_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='Markdown文件路径（相对于static目录）',
               existing_nullable=False)
    op.alter_column('course_documents', 'summary',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='文档摘要',
               existing_nullable=False)
    op.alter_column('course_documents', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='文档标题',
               existing_nullable=False)
    op.alter_column('course_documents', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='文档ID（UUID）',
               existing_nullable=False)
    op.create_table_comment(
        'course_categories',
        '文档目录表',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_course_categories_parent_id'), table_name='course_categories')
    op.drop_index('idx_course_category_parent_order', table_name='course_categories')
    op.create_index('idx_parent_order', 'course_categories', ['parent_id', 'order'], unique=False)
    op.create_index('idx_parent_id', 'course_categories', ['parent_id'], unique=False)
    op.alter_column('course_categories', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('course_categories', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('course_categories', 'order',
               existing_type=mysql.INTEGER(),
               comment='排序顺序',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('course_categories', 'parent_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='父目录ID（NULL表示根目录）',
               existing_nullable=True)
    op.alter_column('course_categories', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='目录名称',
               existing_nullable=False)
    op.alter_column('course_categories', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='目录ID（UUID）',
               existing_nullable=False)
    op.drop_index(op.f('ix_common_tools_visible'), table_name='common_tools')
    op.drop_index(op.f('ix_common_tools_category_id'), table_name='common_tools')
    op.create_index('idx_visible', 'common_tools', ['visible'], unique=False)
    op.create_index('idx_category_order', 'common_tools', ['category_id', 'order'], unique=False)
    op.create_index('idx_category_id', 'common_tools', ['category_id'], unique=False)
    op.drop_index(op.f('ix_artifacts_message_id'), table_name='artifacts')
    op.create_index('idx_message_id', 'artifacts', ['message_id'], unique=False)
    op.drop_index(op.f('ix_ai_tools_visible'), table_name='ai_tools')
    op.drop_index(op.f('ix_ai_tools_toolset_id'), table_name='ai_tools')
    op.drop_index(op.f('ix_ai_tools_tool_id'), table_name='ai_tools')
    op.drop_index('idx_ai_tool_toolset_order', table_name='ai_tools')
    op.drop_index('idx_ai_tool_category_order', table_name='ai_tools')
    op.drop_table('ai_tools')
    op.drop_index(op.f('ix_ai_tool_categories_toolset_id'), table_name='ai_tool_categories')
    op.drop_table('ai_tool_categories')
    op.drop_index(op.f('ix_toolsets_toolset_id'), table_name='toolsets')
    op.drop_table('toolsets')
    op.drop_index('idx_navigation_module_order', table_name='navigation_modules')
    op.drop_table('navigation_modules')
    # ### end Alembic commands ###
