"""add_payment_refunds

Revision ID: d55ebc51c92b
Revises: 32f057d65b28
Create Date: 2026-03-27 09:50:41.220202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd55ebc51c92b'
down_revision: Union[str, Sequence[str], None] = '32f057d65b28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_refunds',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('out_refund_no', sa.String(length=64), nullable=False, comment='商户退款流水号'),
    sa.Column('payment_order_id', mysql.CHAR(length=36), nullable=False, comment='关联支付订单ID'),
    sa.Column('refund_amount', sa.Integer(), nullable=False, comment='退款金额（分）'),
    sa.Column('real_refund_amount', sa.Integer(), nullable=True, comment='实际退款金额（分）'),
    sa.Column('status', sa.Enum('refund_created', 'refund_processing', 'refund_success', 'refund_failed', 'refund_cancelled', name='refundstatus'), nullable=False),
    sa.Column('third_refund_no', sa.String(length=64), nullable=True, comment='工行退款流水号'),
    sa.Column('icbc_refund_response', sa.JSON(), nullable=True, comment='工行退款完整响应'),
    sa.Column('operator_id', mysql.CHAR(length=36), nullable=False, comment='操作人ID'),
    sa.Column('operator_name', sa.String(length=50), nullable=True, comment='操作人姓名'),
    sa.Column('refund_reason', sa.String(length=200), nullable=True, comment='退款原因'),
    sa.Column('submitted_at', sa.DateTime(), nullable=True, comment='发起退款时间'),
    sa.Column('success_at', sa.DateTime(), nullable=True, comment='退款成功时间'),
    sa.Column('failed_at', sa.DateTime(), nullable=True, comment='退款失败时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_order_id'], ['payment_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_refund_created', 'payment_refunds', ['created_at'], unique=False)
    op.create_index('idx_refund_payment', 'payment_refunds', ['payment_order_id'], unique=False)
    op.create_index('idx_refund_status', 'payment_refunds', ['status'], unique=False)
    op.create_index(op.f('ix_payment_refunds_out_refund_no'), 'payment_refunds', ['out_refund_no'], unique=True)
    op.create_index(op.f('ix_payment_refunds_payment_order_id'), 'payment_refunds', ['payment_order_id'], unique=False)
    op.create_index(op.f('ix_payment_refunds_status'), 'payment_refunds', ['status'], unique=False)
    op.add_column('payment_orders', sa.Column('refunded_amount', sa.Integer(), nullable=False, comment='已退款金额（分）'))
    op.add_column('payment_orders', sa.Column('refund_count', sa.Integer(), nullable=False, comment='退款次数'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_orders', 'refund_count')
    op.drop_column('payment_orders', 'refunded_amount')
    op.drop_index(op.f('ix_payment_refunds_status'), table_name='payment_refunds')
    op.drop_index(op.f('ix_payment_refunds_payment_order_id'), table_name='payment_refunds')
    op.drop_index(op.f('ix_payment_refunds_out_refund_no'), table_name='payment_refunds')
    op.drop_index('idx_refund_status', table_name='payment_refunds')
    op.drop_index('idx_refund_payment', table_name='payment_refunds')
    op.drop_index('idx_refund_created', table_name='payment_refunds')
    op.drop_table('payment_refunds')
    # ### end Alembic commands ###
