"""add_enterprise_point_system

Revision ID: ef3a319b300c
Revises: c80318561d4a
Create Date: 2026-03-23 09:03:13.570716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ef3a319b300c'
down_revision: Union[str, Sequence[str], None] = 'c80318561d4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Create enterprises table first (needed for users.enterprise_id foreign key)
    op.create_table('enterprises',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='企业名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='企业代码'),
    sa.Column('status', sa.Enum('active', 'suspended', 'archived', name='enterprisestatus'), nullable=False, comment='企业状态'),
    sa.Column('balance_gratis', sa.Integer(), nullable=False, comment='赠送积分余额（非负）'),
    sa.Column('balance_paid', sa.Integer(), nullable=False, comment='充值积分余额（非负）'),
    sa.Column('debt_points', sa.Integer(), nullable=False, comment='负债积分（透支金额，非负）'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enterprises_code'), 'enterprises', ['code'], unique=True)

    # Step 2: Create model_point_rates table
    op.create_table('model_point_rates',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('model_config_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('tokens_per_point', sa.Integer(), nullable=False, comment='每积分对应token数'),
    sa.Column('separate_io', sa.Boolean(), nullable=False, comment='是否区分输入输出'),
    sa.Column('tokens_per_point_input', sa.Integer(), nullable=True),
    sa.Column('tokens_per_point_output', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_config_id'], ['model_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_point_rates_model_config_id'), 'model_point_rates', ['model_config_id'], unique=True)

    # Step 3: Create point_transactions table
    op.create_table('point_transactions',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('enterprise_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('operator_id', mysql.CHAR(length=36), nullable=True, comment='操作人'),
    sa.Column('type', sa.Enum('recharge', 'gift', 'consume', 'refund', 'adjust', name='pointtransactiontype'), nullable=False, comment='交易类型'),
    sa.Column('source_type', sa.Enum('online_payment', 'offline_payment', 'admin_gift', 'admin_adjust', 'ai_consume', name='pointsourcetype'), nullable=False, comment='来源类型'),
    sa.Column('amount', sa.Integer(), nullable=False, comment='积分金额（正数）'),
    sa.Column('balance_before', sa.Integer(), nullable=False, comment='变动前总积分'),
    sa.Column('balance_after', sa.Integer(), nullable=False, comment='变动后总积分'),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_transactions_created_at'), 'point_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_point_transactions_enterprise_id'), 'point_transactions', ['enterprise_id'], unique=False)

    # Step 4: Create ai_consumptions table
    op.create_table('ai_consumptions',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('enterprise_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('session_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('message_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('model_provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('gratis_points_used', sa.Integer(), nullable=False),
    sa.Column('paid_points_used', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_consumption_enterprise_date', 'ai_consumptions', ['enterprise_id', 'created_at'], unique=False)
    op.create_index('idx_ai_consumption_user_date', 'ai_consumptions', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_consumptions_created_at'), 'ai_consumptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_consumptions_enterprise_id'), 'ai_consumptions', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_ai_consumptions_message_id'), 'ai_consumptions', ['message_id'], unique=False)
    op.create_index(op.f('ix_ai_consumptions_session_id'), 'ai_consumptions', ['session_id'], unique=False)
    op.create_index(op.f('ix_ai_consumptions_user_id'), 'ai_consumptions', ['user_id'], unique=False)

    # Step 5: Add columns to users table as nullable first (for existing users)
    op.add_column('users', sa.Column('enterprise_id', mysql.CHAR(length=36), nullable=True, comment='所属企业ID'))
    op.add_column('users', sa.Column('is_enterprise_admin', sa.Boolean(), nullable=True, comment='是否企业管理员'))
    op.create_index(op.f('ix_users_enterprise_id'), 'users', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_users_is_enterprise_admin'), 'users', ['is_enterprise_admin'], unique=False)

    # Step 6: Insert default enterprise
    op.execute("""
        INSERT INTO enterprises (id, name, code, status, balance_gratis, balance_paid, debt_points, created_at, updated_at)
        VALUES ('default-ent-001', '默认企业', 'default', 'active', 10000, 0, 0, NOW(), NOW())
    """)

    # Step 7: Update existing users to belong to default enterprise
    op.execute("""
        UPDATE users SET enterprise_id = 'default-ent-001', is_enterprise_admin = FALSE WHERE enterprise_id IS NULL
    """)

    # Step 8: Make the columns NOT NULL (MySQL requires existing_type)
    op.alter_column('users', 'enterprise_id', existing_type=mysql.CHAR(length=36), nullable=False)
    op.alter_column('users', 'is_enterprise_admin', existing_type=sa.Boolean(), nullable=False, server_default='0')

    # Step 9: Add foreign key constraint
    op.create_foreign_key(None, 'users', 'enterprises', ['enterprise_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_is_enterprise_admin'), table_name='users')
    op.drop_index(op.f('ix_users_enterprise_id'), table_name='users')
    op.drop_column('users', 'is_enterprise_admin')
    op.drop_column('users', 'enterprise_id')
    op.drop_index(op.f('ix_ai_consumptions_user_id'), table_name='ai_consumptions')
    op.drop_index(op.f('ix_ai_consumptions_session_id'), table_name='ai_consumptions')
    op.drop_index(op.f('ix_ai_consumptions_message_id'), table_name='ai_consumptions')
    op.drop_index(op.f('ix_ai_consumptions_enterprise_id'), table_name='ai_consumptions')
    op.drop_index(op.f('ix_ai_consumptions_created_at'), table_name='ai_consumptions')
    op.drop_index('idx_ai_consumption_user_date', table_name='ai_consumptions')
    op.drop_index('idx_ai_consumption_enterprise_date', table_name='ai_consumptions')
    op.drop_table('ai_consumptions')
    op.drop_index(op.f('ix_point_transactions_enterprise_id'), table_name='point_transactions')
    op.drop_index(op.f('ix_point_transactions_created_at'), table_name='point_transactions')
    op.drop_table('point_transactions')
    op.drop_index(op.f('ix_model_point_rates_model_config_id'), table_name='model_point_rates')
    op.drop_table('model_point_rates')
    op.drop_index(op.f('ix_enterprises_code'), table_name='enterprises')
    op.drop_table('enterprises')
    # ### end Alembic commands ###
